services:
  mongodb:
    image: mongo:5.0.15
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ##build: .  # Build from local Dockerfile instead of using image
    container_name: user-service
    ports:
      - 3001:3001
    env_file:
        - ./.env
    depends_on:
      - mongodb
volumes:
    mongodb_data_container:

    # docker compose -p mongodb_user-service_edu-force up -d
