services:
  mongodb:
    image: mongo:5.0.15
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ##build: .  # Build from local Dockerfile instead of using image
    container_name: user-service
    ports:
      - 3001:3001
    env_file:
        - ./.env
    depends_on:
      - mongodb
      - redis
volumes:
    mongodb_data_container:
    redis_data:

    # docker compose -p mongodb_user-service_edu-force up -d
