version: '3.8'

services:
  mongodb:
    image: mongo:5.0.15
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass 123456  # Thêm mật khẩu (tùy chọn)
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123456", "ping"]  # Sử dụng mật khẩu nếu có
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network
    environment:
      - REDIS_PASSWORD=123456

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - 3001:3001
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=redis  # Dùng tên service thay vì 127.0.0.1
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456  # Nếu Redis có mật khẩu
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mongodb_data_container:
  redis_data:

networks:
  app-network:
    driver: bridge

# docker compose -p mongodb_user-service_edu-force up -d